DEFAULTS = {
    "current_model_year": 2016,
    "current_km": 115000,
    "current_hand": 1,
    "purchase_year": 2016,
    "purchase_month": 1,
    "known_purchase_price": 0,
    "known_current_value": 0,
    "current_value_safety_margin_percent": 5.0,
    "has_existing_loan": False,
    "existing_loan_balance": 0,
    "existing_monthly_payment": 0,
    "existing_remaining_months": 0,
    "existing_interest_rate": 7.0,
    "extra_cash_today": 20000,
    "monthly_saving_capacity": 1000,
    "max_monthly_payment": 2300,
    "next_interest_rate": 7.0,
    "next_loan_months": 60,
    "next_hold_years": 5,
    "annual_km": 18000,
    "max_purchase_price": 250000,
    "max_wait_months": 72,
}

PRIORITY_LABELS = {
    "עלות חודשית מינימלית": "min_cost",
    "רכב חדש ככל האפשר במסגרת האילוצים": "newest_possible",
    "רכב אמין ביותר / סיכון נמוך": "most_reliable",
    "רכב שמחזיק מחיר בעתיד": "best_resale_value",
}
