CURRENT_YEAR = 2026
DEFAULTS = {
    "current_vehicle_value": 80000,
    "current_vehicle_age_years": 10.0,
    "max_current_vehicle_age_years": 15.0,
    "current_annual_depr_rate_percent": 7.0,
    "manual_max_wait_months": 60,
    "has_existing_loan": False,
    "existing_loan_balance": 0,
    "existing_monthly_payment": 0,
    "existing_remaining_months": 0,
    "existing_interest_rate": 7.0,
    "extra_cash_at_purchase": 20000,
    "max_monthly_payment": 2300,
    "next_interest_rate": 7.0,
    "next_loan_months": 60,
    "next_hold_years": 5,
    "annual_km": 18000,
    "max_purchase_price": 250000,
}
